### ISSUE TITLE
Add groupaction to hand that verifies it contains no units

### ISSUE THREAD

**Issue by blakewedwards** [Kertanos/W40kConquest-OCTGN#15]
For Y'varn triggers it's mandatory for both players to put a unit into play if possible, but currently there's no easy way to prove that one can't. In casual matches this doesn't matter but would be nice to have an option for competitive ones.

If you're interested in this feature change, I can create a pull request for it.

**Comment by Kertanos** [comment]
Well it's a stupid rule to begin with, as in real play there is no way to verify an opponent has a unit or not in his hand except for a third party to intervene (wich could be an informant to a player or not...)
So i'll keep it that way until FFG realise they should change yvarn texte to "may".
Until then, people will have to trust each other, as the community we have is more of faithful players than obscure cheaters

**Comment by blakewedwards** [comment]
I don't disagree that it's an unfortunate rule, but it seems highly unlikely that FFG will errata the card at this point. In a competitive environment you can request a judge to confirm the situation, and they are unlikely to be an informant. This would be no different than someone asking for a rules clarification about a card in hand.

If you follow the Conquest competitive scene then you're aware that the 2015 NA champion was disqualified for cheating. Our community is great, but as with any other one there's some <1% of people in it that make the wrong decision once in a while.

I'm willing to create a pull request with the change. Maybe it gets added and hardly anyone uses it.. but some may find it useful. Doesn't seem like it would negatively affect those that don't, up to you.

**Comment by Kertanos** [comment]
I just don't want to put again another function that 0.05% of the players will use. Also it could be used by players to see if their opponent has a unit in hand even if they're not triggering Y'varn right ?
And ifnally, if people want to cheat on octgn, there are tons of way to do it, without even being detected.
Heck you can even change the all code of the plugin and nobody will know...

**Comment by blakewedwards** [comment]
Ah, I'd meant it as something that the player who was unable to play a unit would initiate, not something anyone could do. No worries, I agree it's not an item of frequent use.

One time when an octgn module was erroring out on me I added my own lines to debug it and was a bit surprised that it seemed possible to play like that, thought a checksum or similar would be used at some point to prevent it. Too bad..
