### ISSUE TITLE
Mulligan the number of cards in hand rather than prompting for a number

### ISSUE THREAD

**Issue by blakewedwards** [Kertanos/W40kConquest-OCTGN#16]
I haven't been able to think of a circumstance where mulliganing for a number of cards different than the hand size would occur for Conquest. If the majority of mulligans is for the current number, it seems like it would be convenient to not prompt the player for a value. If there is an occasional/rare situation where this is needed, they can always discard X, shuffle, and draw Y.

If you're interested in this feature change, I can create a pull request for it.

**Comment by Kertanos** [comment]
it's usefull to some people (at last me) when you run mutliple setup hand + a few turn to see how your deck is running, and you have less or more cards in hand than you should but don't want to reset and reload.
It's also a security for people who sometimes press the wrong button (or have a cat) so they can cancel their unintented mulligan

**Comment by blakewedwards** [comment]
The purpose of this module is to facilitate two people playing a game of conquest, and it should be optimized for such.

For those who want to test out hands, I imagine it can accomplish that too. To have a true mulligan from your complete deck, any cards played would need to be returned to either the hand or the deck. If so, you could drag some back to your hand and drag the rest back to the deck, then mulligan for the default 7. The 1 extra click in this circumstance is no different than the 1 extra click that everyone has to do for the default number that they will always require.

To provide security against accidental clicks, perhaps a third confirmation should be added because people may accidentally acknowledge the second? When a cat steps on a keyboard it will also generate multiple key presses, requiring a fourth or perhaps even a fifth confirmation. This line of reasoning is degenerative, only a single confirmation is required.

**Comment by Kertanos** [comment]
you're right on one thing, only a single confirmation is needed, i just didn't remember there was already one.
next update there will only be the numeric confirmation, so everyone's happy ;)

**Comment by blakewedwards** [comment]
Ah cool, yep that's a win-win.
